name: Validation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validation_pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run validation script
        run: python app.py

      - name: Commit and Push Validation Log
        uses: github-actions-x/commit@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "Automated publish of validation_log.txt"
          file_pattern: "data-validation-pipeline/validation_log.txt"
