name:

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  validation_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Run linting
        run: flake8 data_validation_pipeline/ tests/

      - name: Run type checking
        run: mypy data_validation_pipeline/ tests/

      # Step 7: Publish validation_log.txt to the repository
      - name: Commit and Push Validation Log
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: 'main'